稳定通过版本

diff --git a/build-and-run b/build-and-run
--- a/build-and-run
+++ b/build-and-run
@@ -31,7 +31,7 @@ export BuildDir="${ProjectRoot}/build/run"
 export BashLibRoot="${ProjectRoot}/bin/lib-bash"
 export LibBashRepo="https://github.com/kigster/lib-bash"
 
-divider.header() {
+stltest.header() {
   h1.purple "Fractional Division With Remainder: A CMake Project Template with Tests"
   local OIFC=${IFC}
   IFS="|" read -r -a gcc_info <<< "$(gcc --version 2>&1 | tr '\n' '|')"
@@ -41,7 +41,7 @@ divider.header() {
   h1 "${bldylw}CMAKE:  ${bldblu}$(cmake --version | tr '\n' ' ')"
 }
 
-divider.setup() {
+stltest.setup() {
   hl.subtle "Creating Build Folder..."
   run "mkdir -p build/run"
   run "git submodule init && git submodule update"
@@ -49,12 +49,12 @@ divider.setup() {
   [[ -f .idea/workspace.xml ]] || cp .idea/workspace.xml.example .idea/workspace.xml
 }
 
-divider.clean() {
+stltest.clean() {
   hl.subtle "Cleaning output folders..."
   run 'rm -rf bin/d* include/d* lib/*'
 }
 
-divider.build() {
+stltest.build() {
   run "cd build/run"
   run "cmake ../.. "
   run.set-next show-output-on
@@ -63,40 +63,40 @@ divider.build() {
   run "cd ${ProjectRoot}"
 }
 
-divider.tests() {
-  if [[ -f bin/divider_tests ]]; then
+stltest.tests() {
+  if [[ -f bin/stltest ]]; then
     run.set-next show-output-on
-    run "echo && bin/divider_tests"
+    run "echo && bin/stltest"
   else
-    printf "${bldred}Can't find installed executable ${bldylw}bin/divider_tests.${clr}\n"
+    printf "${bldred}Can't find installed executable ${bldylw}bin/stltest.${clr}\n"
     exit 2
   fi
 }
 
-divider.examples() {
-  [[ ! -f bin/divider ]] && {
-    error "You don't have the cmpiled binary yet".
-    exit 3
-  }
+# stltest.examples() {
+#   [[ ! -f bin/stltest ]] && {
+#     error "You don't have the cmpiled binary yet".
+#     exit 3
+#   }
 
-  run.set-all show-output-on
+#   run.set-all show-output-on
 
-  hr
-  run "bin/divider 11 7"
-  hr
-  run "bin/divider 1298798375 94759897"
-  hr
-  run "bin/divider 78 17"
-  hr
+#   hr
+#   run "bin/stltest 11 7"
+#   hr
+#   run "bin/stltest 1298798375 94759897"
+#   hr
+#   run "bin/stltest 78 17"
+#   hr
 
-}
+# }
 
 main() {
-  divider.header
-  divider.setup
-  divider.build
-  divider.tests
-  divider.examples
+  stltest.header
+  stltest.setup
+  stltest.build
+  stltest.tests
+  #stltest.examples
 }
 
 (( $_s_ )) || main
